FROM ubuntu:20.04

RUN apt update && apt-get upgrade -y

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y \
autoconf \
automake \
bison \
bzip2 \
cmake \
flex \
g++ \
gawk \
gcc \
gettext \
git \
gperf \
help2man \
libncurses5-dev \
libstdc++6 \
libtool \
libtool-bin \
make \
patch \
python3-dev \
rsync \
texinfo \
unzip \
wget \
xz-utils \
git \
pkg-config
